version: '3'
services:
  auth-stateless:
    build: .
    container_name: auth-stateless
    ports:
      - 10001:80
    volumes:
      - .:/var/www/html
networks:
  default:
    external:
      name: internal